apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-frontend
  template:
    metadata:
      labels:
        app: app-frontend
    spec:
      containers:
      - name: app-frontend
        image: lucci7/simple-online-store-frontend:v1.0.1
        ports:
        - containerPort: 3000
